// <auto-generated />
using System;
using LeadEnrichment.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LeadEnrichment.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LeadEnrichment.Domain.Leads.Lead", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("ContactName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset?>("EnrichedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Industry")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Score")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyName");

                    b.ToTable("leads", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111001"),
                            CompanyName = "Nordwind Logistik GmbH",
                            ContactEmail = "p.lindgren@nordwind-logistik.example",
                            ContactName = "Petra Lindgren",
                            EnrichedAt = new DateTimeOffset(new DateTime(2026, 6, 30, 9, 12, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Industry = "Logistik",
                            Score = 87,
                            Status = "Qualified"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111002"),
                            CompanyName = "Blaufeld Systemtechnik AG",
                            ContactEmail = "m.vogt@blaufeld-systemtechnik.example",
                            ContactName = "Markus Vogt",
                            EnrichedAt = new DateTimeOffset(new DateTime(2026, 7, 2, 14, 45, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Industry = "Maschinenbau",
                            Score = 64,
                            Status = "Enriched"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111003"),
                            CompanyName = "Rheinallee Consulting Partners",
                            ContactEmail = "s.hoff@rheinallee-consulting.example",
                            ContactName = "Sabine Hoff",
                            EnrichedAt = new DateTimeOffset(new DateTime(2026, 6, 28, 11, 30, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Industry = "Beratung",
                            Score = 52,
                            Status = "Contacted"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111004"),
                            CompanyName = "Kupferbach Elektronik KG",
                            ContactEmail = "j.wetter@kupferbach-elektronik.example",
                            ContactName = "Jonas Wetter",
                            Industry = "Elektronik",
                            Score = 12,
                            Status = "New"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111005"),
                            CompanyName = "Silberpfad Media Solutions",
                            ContactEmail = "a.brummer@silberpfad-media.example",
                            ContactName = "Anke Brummer",
                            EnrichedAt = new DateTimeOffset(new DateTime(2026, 7, 5, 8, 5, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Industry = "Medien",
                            Score = 71,
                            Status = "Enriched"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
